services:
  actual-budget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual_budget
    networks:
      - yohnet
    env_file:
      - actualbudget/.env
      - .env
    volumes:
      - ./actualbudget/data:/data
    healthcheck:
      # Enable health check for the instance
      test: ["CMD-SHELL", "node src/scripts/health-check.js"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
