services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    networks:
      - yohnet
    env_file:
      - aiostreams/.env
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/aiostreams?sslmode=disable
    volumes:
      - ./aiostreams/data:/app/data
    healthcheck:
      test: wget -qO- http://localhost:3000/api/v1/status
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      - mediaflow-proxy
  mediaflow-proxy:
    image: mhdzumair/mediaflow-proxy
    container_name: mediaflow_proxy
    restart: unless-stopped
    networks:
      - yohnet
    env_file:
      - aiostreams/.env.mediaflow
      - .env
