services:
  authentik-server:
    image: ghcr.io/goauthentik/server:2025.10
    container_name: authentik-server
    command: server
    depends_on:
      - "postgres"
    env_file:
      - authentik/.env
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
    restart: unless-stopped
    volumes:
      - ./authentik/media:/media
      - ./authentik/templates:/templates
    networks:
      - yohnet
  authentik-worker:
    image: ghcr.io/goauthentik/server:2025.10
    container_name: authentik-worker
    command: worker
    depends_on:
      - "postgres"
    env_file:
      - authentik/.env
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_USER}
    restart: unless-stopped
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./authentik/media:/media
      - ./authentik/certs:/certs
      - ./authentik/templates:/templates
    networks:
      - yohnet
