services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    user: 1000:1000
    env_file:
      - couchdb/.env
      - .env
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/etc:/opt/couchdb/etc/local.d
    networks:
      - yohnet
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.couchdb.rule=Host(`couchdb.${DOMAIN}`)
      - traefik.http.routers.couchdb.entrypoints=websecure
      - traefik.http.routers.couchdb.tls.certresolver=letsencrypt
      - traefik.http.services.couchdb.loadbalancer.server.port=5984
