services:
  gotify:
    image: gotify/server
    container_name: gotify
    ports:
      - 8040:80
    env_file:
      - gotify/.env
      - .env
    environment:
      GOTIFY_DATABASE_DIALECT: postgres
      GOTIFY_DATABASE_CONNECTION: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/gotify?sslmode=disable
    volumes:
      - "./gotify/data:/app/data"
    restart: always
    networks:
      - yohnet
