services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    networks:
      - yohnet
    ports:
      - 8008:8008
    env_file:
      - synapse/.env
      - .env
    volumes:
      - ./synapse/data:/data
      - ./synapse/bridges:/data/bridges:Z
    restart: unless-stopped
    depends_on:
      - postgres
      - pocket-id
    labels:
      - traefik.enable=true
      - "traefik.http.routers.synapse.rule=Host(`matrix.${DOMAIN}`) && (PathPrefix(`/_matrix`) || PathPrefix(`/_synapse/client`))"
      - traefik.http.routers.synapse.entrypoints=websecure
      - traefik.http.routers.synapse.tls.certresolver=letsencrypt
      - traefik.http.services.synapse.loadbalancer.server.port=8008

  matrix-turnify:
    image: ghcr.io/bpbradley/matrix-turnify:latest
    container_name: matrix-turnify
    restart: unless-stopped
    networks:
      - yohnet
    env_file:
      - synapse/.env.turnify
      - .env
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      - synapse
    labels:
      - traefik.enable=true
      - "traefik.http.routers.matrix-turnify.rule=Host(`matrix.${DOMAIN}`) && PathPrefix(`/_matrix/client/*/voip/turnServer`)"
      - traefik.http.routers.matrix-turnify.entrypoints=websecure
      - traefik.http.routers.matrix-turnify.tls.certresolver=letsencrypt
      - traefik.http.routers.matrix-turnify.priority=32
      - "traefik.http.services.matrix-turnify.loadbalancer.server.port=4499"

  mautrix-telegram:
    container_name: mautrix-telegram
    image: dock.mau.dev/mautrix/telegram:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./synapse/bridges/telegram:/data
    networks:
      - yohnet
    depends_on:
      - synapse

  mautrix-messenger:
    container_name: mautrix-messenger
    image: dock.mau.dev/mautrix/meta:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./synapse/bridges/messenger:/data
    networks:
      - yohnet
    depends_on:
      - synapse

  mautrix-instagram:
    container_name: mautrix-instagram
    image: dock.mau.dev/mautrix/meta:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./synapse/bridges/instagram:/data
    networks:
      - yohnet
    depends_on:
      - synapse

  mautrix-twitter:
    container_name: mautrix-twitter
    image: dock.mau.dev/mautrix/twitter:latest
    restart: unless-stopped
    volumes:
      - ./synapse/bridges/twitter:/data
    networks:
      - yohnet
    depends_on:
      - synapse

  mautrix-bluesky:
    container_name: mautrix-bluesky
    image: dock.mau.dev/mautrix/bluesky:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./synapse/bridges/bluesky:/data
    networks:
      - yohnet
    depends_on:
      - synapse
