services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    env_file:
      - open-webui/.env
      - .env
    networks:
      - yohnet
    volumes:
      - ./open-webui/data:/app/backend/data
