services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    networks:
      - yohnet
    ports:
      - 3000:8080
    volumes:
      - ./open-webui/data:/app/backend/data
