services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    networks:
      - yohnet
    env_file:
      - photoprism/.env
      - .env
    environment:
      PHOTOPRISM_STORAGE_PATH: "/photoprism/storage"
      PHOTOPRISM_ORIGINALS_PATH: "/photoprism/originals"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "${MARIADB_USER}"
      PHOTOPRISM_DATABASE_PASSWORD: "${MARIADB_PASSWORD}"
    volumes:
      - ./photoprism/storage:/photoprism/storage
      - ./st-sync/photos:/photoprism/originals
      - ./st-sync/imports/photos:/photoprism/import
    ports:
      - "2342:2342"
    restart: unless-stopped
    depends_on:
      - mariadb
      - syncthing
