services:
  pihole:
    container_name: pihole
    image: mpgirro/pihole-unbound:latest
    cap_add:
      - NET_BIND_SERVICE # To allow binding to ports < 1024 (e.g., DNS port 53)
      - NET_RAW # To handle raw sockets needed for DHCPv6 and IP verification
      - NET_ADMIN # To modify routing tables and network operations
      - SYS_NICE # To set higher priority for FTL process
      - CHOWN # To change ownership of files if needed
      - SYS_TIME # To set system time if required by FTL
    hostname: pihole
    network_mode: "host"
    env_file:
      - pihole/.env
      - .env
    environment:
      FTLCONF_dns_dnssec: "true"
      FTLCONF_dns_listeningMode: "all"
    volumes:
      - ./pihole/pihole:/etc/pihole:rw
      - ./pihole/dnsmasq.d:/etc/dnsmasq.d:rw
    restart: unless-stopped
