services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    env_file:
      - postiz/.env
      - .env
    environment:
      # === Required Settings
      MAIN_URL: "https://postiz.home.yohli.me"
      FRONTEND_URL: "https://postiz.home.yohli.me"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.home.yohli.me/api"
      JWT_SECRET: "briskly-bagpipe-blunderer-synapse-blazing-ungraded"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postiz?sslmode=disable
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000"
      IS_GENERAL: "true"
      DISABLE_REGISTRATION: "false"
      # === Storage Settings
      STORAGE_PROVIDER: "local"
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
    volumes:
      - ./postiz/config:/config/
      - ./postiz/uploads:/uploads/
    ports:
      - 5000:5000
    networks:
      - yohnet
    depends_on:
      postgres:
        condition: service_started
      postiz-redis:
        condition: service_healthy
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz_redis:/data
    networks:
      - yohnet

volumes:
  postiz_redis:
