include:
  - torrent-scraper.yml

services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    networks:
      - yohnet
    env_file:
      - aiostreams/.env
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/aiostreams?sslmode=disable
    volumes:
      - ./aiostreams/data:/app/data
    healthcheck:
      test: wget -qO- http://localhost:3000/api/v1/status
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
    # depends_on:
    #   - mediaflow-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.aiostreams.rule=Host(`aiostreams.${DOMAIN}`)
      - traefik.http.routers.aiostreams.entrypoints=websecure
      - traefik.http.routers.aiostreams.tls.certresolver=letsencrypt
      - traefik.http.services.aiostreams.loadbalancer.server.port=3000

  aiometadata:
    image: ghcr.io/cedya77/aiometadata:latest
    container_name: aiometadata
    restart: unless-stopped
    networks:
      - yohnet
    env_file:
      - aiometadata/.env
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.aiometadata.rule=Host(`aiometadata.${DOMAIN}`)
      - traefik.http.routers.aiometadata.entrypoints=websecure
      - traefik.http.routers.aiometadata.tls.certresolver=letsencrypt
      - traefik.http.services.aiometadata.loadbalancer.server.port=3232
    volumes:
      - ./aiometadata/data:/app/addon/data
    depends_on:
      aiometadata_redis:
        condition: service_healthy
    tty: true

  aiometadata_redis:
    image: redis:latest
    container_name: aiometadata_redis
    restart: unless-stopped
    networks:
      - yohnet
    volumes:
      - ./aiometadata/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # mediaflow-proxy:
  #   image: mhdzumair/mediaflow-proxy
  #   container_name: mediaflow_proxy
  #   restart: unless-stopped
  #   networks:
  #     - yohnet
  #   env_file:
  #     - aiostreams/.env.mediaflow
  #     - .env
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.mediaflow-proxy.rule=Host(`mediaflow-proxy.${DOMAIN}`)
  #     - traefik.http.routers.mediaflow-proxy.entrypoints=websecure
  #     - traefik.http.routers.mediaflow-proxy.tls.certresolver=letsencrypt
  #     - traefik.http.services.mediaflow-proxy.loadbalancer.server.port=8888
