services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    env_file:
      - vikunja/.env
      - .env
    volumes:
      - ./vikunja/files:/app/vikunja/files
      - ./vikunja/config.yml:/etc/vikunja/config.yml
    depends_on:
      - postgres
      - pocket-id
    restart: unless-stopped
    networks:
      - yohnet
    labels:
      - traefik.enable=true
      - traefik.http.routers.vikunja.rule=Host(`vikunja.${DOMAIN}`)
      - traefik.http.routers.vikunja.entrypoints=websecure
      - traefik.http.routers.vikunja.tls.certresolver=letsencrypt
      - traefik.http.services.vikunja.loadbalancer.server.port=3456
