services:
  vikunja:
    image: vikunja/vikunja
    container_name: vikunja
    env_file:
      - vikunja/.env
      - .env
    volumes:
      - ./vikunja/files:/app/vikunja/files
      - ./vikunja/config.yml:/etc/vikunja/config.yml
    depends_on:
      - postgres
      - pocket-id
    restart: unless-stopped
    networks:
      - yohnet
